import type { ReleaseEntry } from "./types";

export const BUNDLED_CHANGELOG: ReleaseEntry[] = [
  {
    tag: "v1.0.2",
    version: "1.0.2",
    name: "KRYO Client 1.0.2",
    channel: "stable",
    publishedAt: "2026-09-01",
    url: "https://github.com/kryoclient/launcher/releases/tag/v1.0.2",
    assets: [],
    bundled: true,
    notes: [
      "A screen for profiles, a dialog that makes them in one pass, and a new look.",
      "",
      "## Profiles",
      "",
      "- Every profile is a card: version, loader and build, memory, mod count, last played",
      "- Play, edit, duplicate, folder and delete on each card, and delete asks a second time",
      "- Clicking a card selects it; the Play screen links here instead of carrying New and Delete",
      "",
      "## Making one",
      "",
      "- Presets fill the whole thing: Vanilla, Fabric, Forge, OptiFine, or a copy of the current profile",
      "- The same searchable version picker, and the loader build list with Recommended first",
      "- Memory presets bounded by the RAM the machine actually has",
      "- The name writes itself from the version and loader unless you type one; Enter creates",
      "- JVM arguments and window size moved behind Advanced",
      "",
      "## Look",
      "",
      "- Warm near-black, one orange accent, rounded corners",
      "- Manrope ships with the launcher, so the interface renders the same everywhere",
      "- New application icon",
      "",
      "## Fixes",
      "",
      "- Skins and capes load again: Mojang's http texture URLs were refused by the launcher's own content security policy, and are upgraded to https now"
    ].join("\n")
  },
  {
    tag: "v1.0.1",
    version: "1.0.1",
    name: "KRYO Client 1.0.1",
    channel: "stable",
    publishedAt: "2026-08-29",
    url: "https://github.com/kryoclient/launcher/releases/tag/v1.0.1",
    assets: [],
    bundled: true,
    notes: [
      "Loaders, a real version picker, and a Microsoft sign-in that opens a browser window.",
      "",
      "## Loaders",
      "",
      "- Fabric, Quilt, Forge, NeoForge and OptiFine, each with its own build list per Minecraft version",
      "- Forge and NeoForge run the official installer end to end, processors included, so 1.13+ builds are patched properly",
      "- OptiFine is fetched from optifine.net (BMCLAPI as a fallback) and patched against the vanilla jar",
      "- Every loader remembers the exact build on the profile, or follows the recommended one when you leave it on automatic",
      "",
      "## Versions",
      "",
      "- The version dropdown is now a searchable picker over the full Mojang manifest, filtered by release, snapshot or old builds",
      "- Installed versions are marked in the list",
      "",
      "## Accounts",
      "",
      "- Microsoft sign-in opens the real Microsoft page in a window: pick an account, approve, done. No more typing device codes",
      "- Works out of the box; an Azure application ID stays optional for anyone who wants their own",
      "- Sign-out clears the stored browser session so the next login shows the account picker again",
      "",
      "## Speed",
      "",
      "- Verified checksums are cached, so a second launch no longer re-hashes the client jar or the loader's patched output",
      "- A profile whose assets are already complete skips the per-file scan of the whole asset index",
      "- Install only still runs the full verification pass",
      "",
      "## Mods",
      "",
      "- Modrinth search follows the profile loader instead of always asking for Fabric builds",
      "",
      "## Fixes",
      "",
      "- Natives are unpacked into the base version folder, which is where the launch command actually looks for them",
      "- The classpath keeps one jar per artifact, so loader libraries no longer collide with the vanilla ones",
      "- Versions that inherit from a pre-1.13 release keep their launch arguments",
      "- Libraries that a loader builds locally are no longer downloaded and are no longer reported as failures",
      "",
      "## Also",
      "",
      "- New application icon, on the window, the taskbar and the installer",
      "- This screen: every release and beta, straight from GitHub"
    ].join("\n")
  },
  {
    tag: "v1.0.0",
    version: "1.0.0",
    name: "KRYO Client 1.0",
    channel: "stable",
    publishedAt: "2026-08-24",
    url: "https://github.com/kryoclient/launcher/releases/tag/v1.0.0",
    assets: [],
    bundled: true,
    notes: [
      "The first public build.",
      "",
      "- Installs any version Mojang lists, verifying every file by sha1",
      "- Fabric through the official Fabric meta API",
      "- Finds your Java, or downloads a matching Adoptium runtime",
      "- Mod browser over Modrinth: install, toggle and remove per profile",
      "- Offline accounts and Microsoft licences",
      "- Skins and capes from your Minecraft account",
      "- Server list pinged for real, SRV records included",
      "- Unlimited profiles, each with its own version, loader, RAM, JVM flags and window size"
    ].join("\n")
  }
];
